### ISSUE TITLE
Request: support CIDv1 in explorer.loopring.io or block CIDv1 from being used in the minting UI

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring-explorer#22]
https://github.com/Loopring/loopring-wallet-feedback/issues/193#issue-1167190912

**Comment by shad-k** [comment]
As mentioned in the issue linked to this is something that should either be fixed in the minting UI or in the conversion of CID to nftID. As far as I can understand no change is needed on the explorer frontend for this. We can close this issue if my assumption is correct.
